name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      - name: Decode signing secret key ring file
        run: |
          echo "${{secrets.MAVEN_GPG_PRIVATE_KEY}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      - name: Publish to MavenCentral
        run: ./gradlew publish -PossrhUsername=${{secrets.MAVEN_CENTRAL_NAME}} -PossrhPassword=${{secrets.MAVEN_CENTRAL_TOKEN}} -Psigning.keyId=${{secrets.MAVEN_GPG_KEY_ID}} -Psigning.password=${{secrets.MAVEN_GPG_PASSPHRASE}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.MAVEN_CENTRAL_NAME}}
          OSSRH_PASSWORD: ${{secrets.MAVEN_CENTRAL_TOKEN}}